### PR TITLE
New Theme Meteor 

### PR DESCRIPTION
**Pull request by stagfoo**
A darkish theme inspired by the Artwork [Meteor by Nina Geometrieva](https://dribbble.com/shots/1355879-Meteor-Wallpaper). Best Paired with the Flatron theme.

screen shot 2015-10-23 at 8 39 23 am

### CODE REVIEW

**Comment by GianlucaGuarini** [comment]
You forgot a comma in the json file. Please fix the issue and I will be happy to merge the theme

**Comment by stagfoo** [comment]
Hey @GianlucaGuarini 
Updated, i ran it through jsonlint to double check.
Let me know if there is anything else i need to do

**Comment by GianlucaGuarini** [comment]
@stagfoo could you please fix the git conflicts as well please?

**Comment by stagfoo** [comment]
Cool it thinks its all good now, looks like it passed all the checks. Sorry for the delay, i haven't merged upstream before, kind of new to forks.

**Comment by GianlucaGuarini** [comment]
@stagfoo thank you

**Pull request merged**
