### PR TITLE
add `Humane.tmTheme`

### PR DESCRIPTION
**Pull request by rivy**
(by Damien Guard)

### CODE REVIEW

**Comment by rivy** [comment]
@GianlucaGuarini 
Is there some issue blocking the merge on this pull request?

**Comment by GianlucaGuarini** [comment]
Hi @rivy your pull is not blocked. It's just not in sync with the repo. Could you fix it please?

**Comment by rivy** [comment]
Done. Rebased to master HEAD, with a passing build.

**Comment by GianlucaGuarini** [comment]
thanks

**Pull request merged**
