### PR TITLE
Two new Themes

### PR DESCRIPTION
**Pull request by robengrobban**

### CODE REVIEW

**Comment by robengrobban** [comment]
Fixed the problems and the nameing! Would be nice to have this merged

**Comment by robengrobban** [comment]
Can someone take a look into merging this?

**Comment by GianlucaGuarini** [comment]
@robengrobban as I already said [here](https://github.com/Colorsublime/Colorsublime-Themes/pull/309#discussion_r89053104) please fix the typo and your pull request will be merged and be patient it's Sunday and nobody is gonna die if your pull request (once you will fix your typo) is gonna be merged next week

**Comment by robengrobban** [comment]
Hi! I don't know if you looked into this new pull request (This one). But in this one, it is named corectly... And i think that is what you mean with typo... Other wise, responde

**Pull request closed without merging**
