### PR TITLE
Adding 00_bashling theme, and sort the authors names in the README

### PR DESCRIPTION
**Pull request by lingtalfi**

### CODE REVIEW

**Comment by blopker** [comment]
Is putting '00_' in the name just an attempt to get to the top of the sort list?

**Comment by lingtalfi** [comment]
Yes.
Is that okay?

**Comment by blopker** [comment]
I say 'no', but I'll let @GianlucaGuarini make the call.

**Comment by lingtalfi** [comment]
Sure.

**Comment by GianlucaGuarini** [comment]
@lingtalfi thanks for your pull request. But I would prefer a new one where you just submit your theme without '00_' and without changing the order of the authors in the readme file ( let us doing it ).

**Comment by lingtalfi** [comment]
You've got it.

**Pull request closed without merging**
