### PR TITLE
Added new theme: bashling

### PR DESCRIPTION
**Pull request by lingtalfi**

### CODE REVIEW

**Comment by GianlucaGuarini** [comment]
thank you

**Comment by lingtalfi** [comment]
Is it possible to have my name and link to my github in the theme creators list?

**Comment by GianlucaGuarini** [comment]
yes of course

**Comment by lingtalfi** [comment]
thank you

**Comment by GianlucaGuarini** [comment]
...pull request adding your name into the readme file

**Comment by lingtalfi** [comment]
You’ve got it!

**Pull request merged**
