### PR TITLE
Fix #130: check that Title has no surrounding whitespace

### LINKED ISSUE #130: Disallow spaces in front of theme Titles?
I noticed some themes take advantage of Title sorting to be shown first:
```json
{
    "Title": " 1337",
    "FileName": "1337.tmTheme",
    "Author": "Mark Michos",
    "Description": "A color scheme for dark Sublime Text themes."
}
{
    "Title": " Dark Room (Normal)",
    "FileName": "DarkRoomNormal.tmTheme",
    "Author": "Neil Cresswell",
    "Description": "Easy on eyes dark theme with accented comments and GitGutter support. See https://github.com/NeilCresswell/themes for other IDEs."
}
```
This is a little unfair to the other themes which don't do this. Maybe this should be checked for in a test and rejected?

### PR DESCRIPTION
**Pull request by blopker**
Added a test to make sure people don't put whitespace in their theme titles so they get sorted first.

Also added a more robust file/json test, found an error in the json.

### CODE REVIEW

**Comment by GianlucaGuarini** [comment]
You have done a bit more than checking the tralling white spaces in the themes names I will pull and check bettter your branch before merging it into the master. Thanks

**Comment by blopker** [comment]
Yeah, I think I had too much coffee that day.

The main other change was to use `require` to load themes.json so other tests wouldn't have to keep using JSON.parse on it. If the json is malformed I just set it to an array and let the linter let tell the user what the issues are.

**Comment by blopker** [comment]
Also another change I would have liked to make is to use the async filer reader here: https://github.com/Colorsublime/Colorsublime-Themes/blob/master/tests/themes-parsing.spec.js#L247
It would speed up that test significantly. 

But I stopped myself before this PR got too out of control ;)

**Comment by GianlucaGuarini** [comment]
We can optimize a lot the theme parsing script but it's a fork of [this one](https://github.com/ajaxorg/ace/blob/master/tool/tmtheme.js) that sucks.. I wouldn't waste time on it unless it will somehow break the site

**Comment by blopker** [comment]
> why have you used a try/catch here?

If parsing the JSON fails I wanted the linter test to tell the user and not node's cryptic error. Also, now other tests are free to assume that global is a JSON list.

**Comment by GianlucaGuarini** [comment]
I have removed it your try/catch block. I think you gave me a good hint, I prefer to use the default node require call to load the themes.json avoiding the jsonlint dependency. It makes everything a bit simpler. I would not invest too much time on these tests, in the end we just need to use them to check the what gets pushed on this repo.

**Pull request merged**
