### PR TITLE
Added two Wildlife theme (Day and Night)

### PR DESCRIPTION
**Pull request by tushortz**
Added two Wildlife theme (Day and Night)

### CODE REVIEW

**Comment by GianlucaGuarini** [comment]
could you fix the issues. Your pull request does not pass your tests

**Comment by tushortz** [comment]
I sent an email to the email provided. I don't know how to run the npm
dependency test. But I'll check the Travis build info

**Comment by GianlucaGuarini** [comment]
could [this]https://github.com/Colorsublime/Colorsublime-Themes#run-the-tests help?

**Comment by tushortz** [comment]
No it didn't help at all. Is there a program that needs to be downloaded before the npm dependency test can be run. And will it be from bash @GianlucaGuarini

**Comment by tushortz** [comment]
I think I can fix it. I'll check again and create a new pull request. It's the spaces causing the failed tests

**Comment by tushortz** [comment]
I know i've made a lot of commits. I have now passed the test but will close this now and create a new fork and pull request to save memory

**Pull request closed without merging**
